name: review888
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^11.0.0
  fluttertoast: ^9.0.0
  http: ^1.2.2
  webview_flutter: ^4.4.2
  image_cropper: ^12.2.1
  image_picker: ^1.0.5
  path_provider: ^2.0.11
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.7
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  flutter_dotenv: ^6.0.1
  youtube_player_iframe: ^5.2.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  network_image_mock: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env

